twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        cartservice: '@App\Service\CartServiceInterface'
        authservice: '@App\Service\AuthService'

when@test:
    twig:
        strict_variables: true
